### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tacaswell**
@benjaminabel turned travis on on the matplotlib org version of this repo and re-created the PR here.

### CODE REVIEW

**Comment by tacaswell** [comment]
@benjaminabel Can you update the README badge to point at the matplotlib org version?

**Comment by ghost** [comment]
As I mentioned in the original PR, I think we should eliminate every code that tries to retrieve the data from yahoo, and **concentrate this lib in plotting financial charts**. We could rewrite examples loading data from  `csv` files and  `pandas-datareader`.

**Comment by tacaswell** [comment]
@benjaminabel That sounds reasonable to me!

**Comment by tacaswell** [comment]
It looks like we are missing a `.travis.yml` file

**Comment by akkana** [comment]
FWIW, looks like pandas_datareader can't read either yahoo or google finance data any more either.
https://stackoverflow.com/questions/44045158/python-pandas-datareader-no-longer-works-for-yahoo-finance-changed-url
has a workaround (probably temporary) for yahoo; the google example there no longer works. It's not clear if there's a reasonable solution any more for reading finance data from python.

**Comment by tacaswell** [comment]
Can we just use synthetic data for the tests / examples?  Real data is cooler, but generated data will always work.  

You can set the random number seed (`np.random.seed(19680801)` (the number JDH's birthday and is what we use in Matplotlib when ever we need a seed))  so that the results are reproducible.

**Comment by ghost** [comment]
I prefer real data as it will be the common use cases, some `csv` from real providers seems reasonable.

**Comment by ghost** [comment]
@tacaswell  now we can remove the functions used to fetch data from yahoo. Are you OK?

**Comment by tacaswell** [comment]
Yeah, they do not work.  It is technically an API break, but it is already broken.

**Pull request merged**
