### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tacaswell**
Some work to move this closer to releasable.

The yahoo data retriever seems very broken.  It is required for all of the examples to run.

There is a spin-off project from pandas which handles fetching the data : https://github.com/pydata/pandas-datareader.  I have started to convert the examples to use it.

### CODE REVIEW

**Comment by ghost** [comment]
Hi, why didn't you merged this PR?

**Comment by tacaswell** [comment]
Because it does not pass the tests (because the yahoo data source is broken).

**Comment by ghost** [comment]
Where are located the tests?

**Comment by tacaswell** [comment]
Sorry, I take that back, it's the examples that don't run.

**Comment by ghost** [comment]
Maybe we could add a Travis job to run e2e tests on the examples folder to have infos about that. Can I continue your PR in that way?

**Comment by tacaswell** [comment]
@benjaminabel Please do!

**Comment by tacaswell** [comment]
closing in favor of #9

**Pull request closed without merging**
